id: gcp_config
namespace: gcp

tasks:
  - id: "gcp_create_bucket"
    type: "io.kestra.plugin.gcp.gcs.CreateBucket"
    name: "{{ kv('GCP_BUCKET_NAME')}}"
    storageClass: REGIONAL
    ifExists: SKIP

  - id: "gcp_create_dataset"
    type: "io.kestra.plugin.gcp.bigquery.CreateDataset"
    name: "{{ kv('GCP_DATASET')}}"
    ifExists: SKIP

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{ kv('GCP_CREDS')}}"
      projectId: "{{ kv('GCP_PROJECT_ID')}}"
      location: "{{ kv('GCP_LOCATION')}}"
      bucket: "{{ kv('GCP_BUCKET_NAME')}}"